import {
  assetTypeHoldingDetails,
  blackListItems,
  entityHitResult,
  externalRatingAgencies,
  externalRatingMeaning,
  financialInstitutionGroups,
  generalEnterpriseGroups,
  greyListItems,
  holdingAssetTypeRows,
  holdingMemberCompanyRows,
  internalAnnualRatingRecords,
  largeCustomerOverview,
  largeCustomerTableData,
  largeCustomerTrendData,
  memberCompanyHoldingDetails,
  nameListStats,
  ratingEntitySummary,
  singleLargeCustomerAssetExposure,
  singleLargeCustomerCompanyExposure,
  singleLargeCustomerWarningCompanyDistribution,
  singleLargeCustomerWarningMetrics,
  singleLargeCustomerWarningTrend,
  vankeMemberCompanyComparisonData,
  vankeMetrics,
  vankeRiskDrilldown,
  vankeTrendData,
  vankeWarningInsuranceSummary,
  warningInsuranceMemberDistribution,
  warningInsuranceOverview,
  warningInsuranceTrendData,
  whiteListItems,
} from '../mockData';

export {
  assetTypeHoldingDetails,
  blackListItems,
  entityHitResult,
  externalRatingAgencies,
  externalRatingMeaning,
  financialInstitutionGroups,
  generalEnterpriseGroups,
  greyListItems,
  holdingAssetTypeRows,
  holdingMemberCompanyRows,
  internalAnnualRatingRecords,
  largeCustomerOverview,
  largeCustomerTableData,
  largeCustomerTrendData,
  memberCompanyHoldingDetails,
  nameListStats,
  ratingEntitySummary,
  singleLargeCustomerAssetExposure,
  singleLargeCustomerCompanyExposure,
  singleLargeCustomerWarningCompanyDistribution,
  singleLargeCustomerWarningMetrics,
  singleLargeCustomerWarningTrend,
  vankeMemberCompanyComparisonData,
  vankeMetrics,
  vankeRiskDrilldown,
  vankeTrendData,
  vankeWarningInsuranceSummary,
  warningInsuranceMemberDistribution,
  warningInsuranceOverview,
  warningInsuranceTrendData,
  whiteListItems,
};

// Mirrors the desktop-rendered Vanke concentration chart labels used by the mobile demo.
// The source mockData.ts is intentionally left unchanged.
export const vankeConcentrationTrendRows = [
  { month: '2025-05', exposure: 720, concentration: 81, threshold: 90 },
  { month: '2025-04', exposure: 705, concentration: 81, threshold: 90 },
  { month: '2025-03', exposure: 690, concentration: 80, threshold: 90 },
  { month: '2025-02', exposure: 675, concentration: 79, threshold: 90 },
  { month: '2025-01', exposure: 660, concentration: 77, threshold: 90 },
  { month: '2024-12', exposure: 640, concentration: 75, threshold: 90 },
  { month: '2024-11', exposure: 625, concentration: 74, threshold: 90 },
  { month: '2024-10', exposure: 610, concentration: 73, threshold: 90 },
  { month: '2024-09', exposure: 585, concentration: 72, threshold: 90 },
  { month: '2024-08', exposure: 560, concentration: 70, threshold: 90 },
  { month: '2024-07', exposure: 535, concentration: 69, threshold: 90 },
  { month: '2024-06', exposure: 520, concentration: 68, threshold: 90 },
];

// Values below mirror existing desktop-local constants in src/App.tsx.
export const counterpartyTrendData = [
  { label: '2024-12', value: 210.32, mom: '-' },
  { label: '2025-01', value: 223.45, mom: '↑ 6.24%' },
  { label: '2025-02', value: 236.81, mom: '↑ 5.98%' },
  { label: '2025-03', value: 249.87, mom: '↑ 5.52%' },
  { label: '2025-04', value: 264.59, mom: '↑ 5.89%' },
  { label: '2025-05', value: 286.35, mom: '↑ 8.21%' },
];

export const counterpartyMemberData = [
  { label: '银行', value: 100.12 },
  { label: '证券', value: 72.35 },
  { label: '信托', value: 48.26 },
  { label: '资管', value: 32.18 },
  { label: '基金', value: 21.66 },
  { label: '其他', value: 11.78 },
];

export const counterpartyAssetData = [
  { label: '债券', value: 167.28 },
  { label: '股票', value: 68.74 },
  { label: '基金', value: 28.31 },
  { label: '非标', value: 14.22 },
  { label: '现金及其他', value: 7.8 },
];

export const counterpartyStackedData = [
  { label: '银行', total: 100.12, values: [52.36, 28.21, 12.15, 5.4, 2] },
  { label: '证券', total: 72.35, values: [36.28, 20.14, 8.05, 4.7, 3.18] },
  { label: '信托', total: 48.26, values: [22.31, 12.36, 7.56, 3.11, 2.92] },
  { label: '资管', total: 32.18, values: [15.26, 7.85, 5.12, 2.15, 1.8] },
  { label: '基金', total: 21.66, values: [9.87, 6.12, 3.44, 1.49, 0.74] },
  { label: '其他', total: 11.78, values: [5.2, 3.1, 1.6, 1.4, 0.48] },
];

export const counterpartyStackLegend = ['债券', '股票', '基金', '非标', '其他'];

export const singleLargeMetrics = [
  { title: '总持仓规模', value: '285.53', unit: '亿元', change: '较上月 +12.80 亿元', subChange: '较年初 +4.70%' },
  { title: '最大专业公司敞口', value: '137.01', unit: '亿元', change: '银行, 占比 48.01%' },
  { title: '出险预警金额', value: '217.82', unit: '亿元', change: '' },
  { title: '黑灰名单', value: '黑名单 4 条', unit: '', change: '灰名单 6 条' },
  { title: '内部最新评级', value: '7A', unit: '', change: '2025-06-20' },
];

export const currentWarningSummaryRows = [
  { key: 'defaulted', label: '出险', valueKey: 'defaulted' },
  { key: 'major', label: '重大预警', valueKey: 'major' },
  { key: 'second', label: '二级预警', valueKey: 'second' },
  { key: 'first', label: '一级预警', valueKey: 'first' },
] as const;

export const singleLargeWarningDrilldown = [
  {
    key: 'defaulted',
    label: '出险金额',
    badge: '出险',
    amount: 20,
    members: [
      {
        name: '寿险',
        amount: 8,
        subsidiaries: [{ name: '万科企业股份有限公司', amount: 5 }, { name: '万科地产上海有限公司', amount: 3 }],
        details: [
          {
            company: '万科企业股份有限公司',
            projectName: '万科企业股份有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '非标',
            amount: 5,
          },
          {
            company: '万科地产上海有限公司',
            projectName: '万科地产上海有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '非标',
            amount: 3,
          },
        ],
      },
      {
        name: '银行',
        amount: 7,
        subsidiaries: [{ name: '万科服务有限公司', amount: 4 }, { name: '万科地产华南有限公司', amount: 3 }],
        details: [
          {
            company: '万科服务有限公司',
            projectName: '万科服务有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 4,
          },
          {
            company: '万科地产华南有限公司',
            projectName: '万科地产华南有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 3,
          },
        ],
      },
      {
        name: '信托',
        amount: 5,
        subsidiaries: [{ name: '万科商业管理有限公司', amount: 5 }],
        details: [
          {
            company: '万科商业管理有限公司',
            projectName: '万科商业管理有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '信托',
            businessType: '非标',
            amount: 5,
          },
        ],
      },
    ],
  },
  {
    key: 'major',
    label: '重大预警金额',
    badge: '重大预警',
    amount: 30,
    members: [
      {
        name: '银行',
        amount: 12,
        subsidiaries: [{ name: '万科服务有限公司', amount: 5 }, { name: '万科地产华南有限公司', amount: 4 }, { name: '万科物业发展有限公司', amount: 3 }],
        details: [
          {
            company: '万科（重庆）企业有限公司',
            projectName: '平安-万科重庆合等价不动产债券投资计划',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '非标',
            amount: 5,
          },
          {
            company: '万科地产华南有限公司',
            projectName: '万科地产华南有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 4,
          },
          {
            company: '万科物业发展有限公司',
            projectName: '万科物业发展有限公司风险预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 3,
          },
        ],
      },
      {
        name: '寿险',
        amount: 10,
        subsidiaries: [{ name: '万科企业股份有限公司', amount: 6 }, { name: '万科地产上海有限公司', amount: 4 }],
        details: [
          {
            company: '万科企业股份有限公司',
            projectName: '万科企业股份有限公司重大预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '债券',
            amount: 6,
          },
          {
            company: '万科地产上海有限公司',
            projectName: '万科地产上海有限公司重大预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '非标',
            amount: 4,
          },
        ],
      },
      {
        name: '信托',
        amount: 8,
        subsidiaries: [{ name: '万科地产北京有限公司', amount: 5 }, { name: '万科商业管理有限公司', amount: 3 }],
        details: [
          {
            company: '万科地产北京有限公司',
            projectName: '万科地产北京有限公司重大预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '信托',
            businessType: '非标',
            amount: 5,
          },
          {
            company: '万科商业管理有限公司',
            projectName: '万科商业管理有限公司重大预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '信托',
            businessType: '非标',
            amount: 3,
          },
        ],
      },
    ],
  },
  {
    key: 'second',
    label: '二级预警金额',
    badge: '二级预警',
    amount: 50,
    members: [
      {
        name: '银行',
        amount: 20,
        subsidiaries: [{ name: '万科服务有限公司', amount: 8 }, { name: '万科地产华东有限公司', amount: 7 }, { name: '万科物流发展有限公司', amount: 5 }],
        details: [
          {
            company: '万科服务有限公司',
            projectName: '万科服务有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 8,
          },
          {
            company: '万科地产华东有限公司',
            projectName: '万科地产华东有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 7,
          },
          {
            company: '万科物流发展有限公司',
            projectName: '万科物流发展有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '债券',
            amount: 5,
          },
        ],
      },
      {
        name: '寿险',
        amount: 15,
        subsidiaries: [{ name: '万科企业股份有限公司', amount: 9 }, { name: '万科地产深圳有限公司', amount: 6 }],
        details: [
          {
            company: '万科企业股份有限公司',
            projectName: '万科企业股份有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '债券',
            amount: 9,
          },
          {
            company: '万科地产深圳有限公司',
            projectName: '万科地产深圳有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '非标',
            amount: 6,
          },
        ],
      },
      {
        name: '证券',
        amount: 10,
        subsidiaries: [{ name: '万科物业服务有限公司', amount: 6 }, { name: '万科城市更新有限公司', amount: 4 }],
        details: [
          {
            company: '万科物业服务有限公司',
            projectName: '万科物业服务有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '证券',
            businessType: '股票',
            amount: 6,
          },
          {
            company: '万科城市更新有限公司',
            projectName: '万科城市更新有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '证券',
            businessType: '股票',
            amount: 4,
          },
        ],
      },
      {
        name: '资管',
        amount: 5,
        subsidiaries: [{ name: '万科商业管理有限公司', amount: 5 }],
        details: [
          {
            company: '万科商业管理有限公司',
            projectName: '万科商业管理有限公司二级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '资管',
            businessType: '基金',
            amount: 5,
          },
        ],
      },
    ],
  },
  {
    key: 'first',
    label: '一级预警金额',
    badge: '一级预警',
    amount: 80,
    members: [
      {
        name: '银行',
        amount: 30,
        subsidiaries: [{ name: '万科服务有限公司', amount: 12 }, { name: '万科地产华南有限公司', amount: 10 }, { name: '万科物业发展有限公司', amount: 8 }],
        details: [
          {
            company: '万科服务有限公司',
            projectName: '万科服务有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 12,
          },
          {
            company: '万科地产华南有限公司',
            projectName: '万科地产华南有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 10,
          },
          {
            company: '万科物业发展有限公司',
            projectName: '万科物业发展有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '银行',
            businessType: '非标',
            amount: 8,
          },
        ],
      },
      {
        name: '寿险',
        amount: 25,
        subsidiaries: [{ name: '万科企业股份有限公司', amount: 15 }, { name: '万科地产上海有限公司', amount: 10 }],
        details: [
          {
            company: '万科企业股份有限公司',
            projectName: '万科企业股份有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '债券',
            amount: 15,
          },
          {
            company: '万科地产上海有限公司',
            projectName: '万科地产上海有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '寿险',
            businessType: '非标',
            amount: 10,
          },
        ],
      },
      {
        name: '证券',
        amount: 15,
        subsidiaries: [{ name: '万科城市更新有限公司', amount: 9 }, { name: '万科物流发展有限公司', amount: 6 }],
        details: [
          {
            company: '万科城市更新有限公司',
            projectName: '万科城市更新有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '证券',
            businessType: '股票',
            amount: 9,
          },
          {
            company: '万科物流发展有限公司',
            projectName: '万科物流发展有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '证券',
            businessType: '股票',
            amount: 6,
          },
        ],
      },
      {
        name: '信托',
        amount: 10,
        subsidiaries: [{ name: '万科地产北京有限公司', amount: 6 }, { name: '万科商业管理有限公司', amount: 4 }],
        details: [
          {
            company: '万科地产北京有限公司',
            projectName: '万科地产北京有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '信托',
            businessType: '非标',
            amount: 6,
          },
          {
            company: '万科商业管理有限公司',
            projectName: '万科商业管理有限公司一级预警跟踪项目',
            warningStartDate: '2025-01-01',
            memberCompany: '信托',
            businessType: '非标',
            amount: 4,
          },
        ],
      },
    ],
  },
] as const;

export type MobileVankeRiskProjectDetail = {
  company: string;
  projectName: string;
  warningStartDate: string;
  memberCompany: string;
  businessType: string;
  amount: number;
};

export const mobileVankeRiskProjectDetails = {
  defaulted: {
    寿险: [
      {
        company: '万科企业股份有限公司',
        projectName: '万科企业股份有限公司出险项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '债券',
        amount: 5,
      },
      {
        company: '万科地产上海有限公司',
        projectName: '万科地产上海有限公司出险项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '非标',
        amount: 3,
      },
    ],
    银行: [
      {
        company: '万科服务有限公司',
        projectName: '万科服务有限公司出险项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 4,
      },
      {
        company: '万科地产华南有限公司',
        projectName: '万科地产华南有限公司出险项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 3,
      },
    ],
    信托: [
      {
        company: '万科商业管理有限公司',
        projectName: '万科商业管理有限公司出险项目',
        warningStartDate: '2025-01-01',
        memberCompany: '信托',
        businessType: '非标',
        amount: 5,
      },
    ],
  },
  major: {
    银行: [
      {
        company: '万科（重庆）企业有限公司',
        projectName: '平安-万科重庆合等价不动产债券投资计划',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '非标',
        amount: 5,
      },
      {
        company: '万科地产华南有限公司',
        projectName: '万科地产华南有限公司风险预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 4,
      },
      {
        company: '万科物业发展有限公司',
        projectName: '万科物业发展有限公司风险预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 3,
      },
    ],
    寿险: [
      {
        company: '万科企业股份有限公司',
        projectName: '万科企业股份有限公司重大预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '债券',
        amount: 6,
      },
      {
        company: '万科地产上海有限公司',
        projectName: '万科地产上海有限公司重大预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '非标',
        amount: 4,
      },
    ],
    信托: [
      {
        company: '万科地产北京有限公司',
        projectName: '万科地产北京有限公司重大预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '信托',
        businessType: '非标',
        amount: 5,
      },
      {
        company: '万科商业管理有限公司',
        projectName: '万科商业管理有限公司重大预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '信托',
        businessType: '非标',
        amount: 3,
      },
    ],
  },
  second: {
    银行: [
      {
        company: '万科服务有限公司',
        projectName: '万科服务有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 8,
      },
      {
        company: '万科地产华东有限公司',
        projectName: '万科地产华东有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 7,
      },
      {
        company: '万科物流发展有限公司',
        projectName: '万科物流发展有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '债券',
        amount: 5,
      },
    ],
    寿险: [
      {
        company: '万科企业股份有限公司',
        projectName: '万科企业股份有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '债券',
        amount: 9,
      },
      {
        company: '万科地产深圳有限公司',
        projectName: '万科地产深圳有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '非标',
        amount: 6,
      },
    ],
    证券: [
      {
        company: '万科物业服务有限公司',
        projectName: '万科物业服务有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '证券',
        businessType: '股票',
        amount: 6,
      },
      {
        company: '万科城市更新有限公司',
        projectName: '万科城市更新有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '证券',
        businessType: '股票',
        amount: 4,
      },
    ],
    资管: [
      {
        company: '万科商业管理有限公司',
        projectName: '万科商业管理有限公司二级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '资管',
        businessType: '基金',
        amount: 5,
      },
    ],
  },
  first: {
    银行: [
      {
        company: '万科服务有限公司',
        projectName: '万科服务有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 12,
      },
      {
        company: '万科地产华南有限公司',
        projectName: '万科地产华南有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 10,
      },
      {
        company: '万科物业发展有限公司',
        projectName: '万科物业发展有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '银行',
        businessType: '非标',
        amount: 8,
      },
    ],
    寿险: [
      {
        company: '万科企业股份有限公司',
        projectName: '万科企业股份有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '债券',
        amount: 15,
      },
      {
        company: '万科地产上海有限公司',
        projectName: '万科地产上海有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '寿险',
        businessType: '非标',
        amount: 10,
      },
    ],
    证券: [
      {
        company: '万科城市更新有限公司',
        projectName: '万科城市更新有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '证券',
        businessType: '股票',
        amount: 9,
      },
      {
        company: '万科物流发展有限公司',
        projectName: '万科物流发展有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '证券',
        businessType: '股票',
        amount: 6,
      },
    ],
    信托: [
      {
        company: '万科地产北京有限公司',
        projectName: '万科地产北京有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '信托',
        businessType: '非标',
        amount: 6,
      },
      {
        company: '万科商业管理有限公司',
        projectName: '万科商业管理有限公司一级预警跟踪项目',
        warningStartDate: '2025-01-01',
        memberCompany: '信托',
        businessType: '非标',
        amount: 4,
      },
    ],
  },
} satisfies Record<string, Record<string, MobileVankeRiskProjectDetail[]>>;

export type SentimentRiskLevel = 'high' | 'medium';

export type SentimentFeedItem = {
  id: string;
  title: string;
  customer: string;
  customerName: string;
  date: string;
  updateDate: string;
  level: SentimentRiskLevel;
  riskLevel: SentimentRiskLevel;
  source: string;
  tags: string[];
  summary: string;
  body: string;
  content: string;
  aiInsight: string;
};

export const singleLargeCustomerSentimentFeed: Record<SentimentRiskLevel, SentimentFeedItem[]> = {
  high: [
    {
      id: 'sentiment-high-001',
      title: '万科推进债务展期安排，部分融资工具兑付压力上升',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-18',
      updateDate: '2025-06-18',
      level: 'high',
      riskLevel: 'high',
      source: '公开舆情 / 新闻监测',
      tags: ['债务展期', '融资压力', '负面舆情'],
      summary: '市场消息显示，万科相关债务展期安排仍在推进，部分融资工具存在再融资压力，需关注后续兑付进展。',
      body: '近期市场消息显示，万科相关债务展期安排仍在推进，部分融资工具存在再融资压力。结合当前持仓规模、预警出险情况及评级变化，该舆情可能进一步影响集团内部风险判断。建议持续跟踪后续兑付安排、融资工具展期进展及相关主体公告。',
      content: '近期市场消息显示，万科相关债务展期安排仍在推进，部分融资工具存在再融资压力。结合当前持仓规模、预警出险情况及评级变化，该舆情可能进一步影响集团内部风险判断。建议持续跟踪后续兑付安排、融资工具展期进展及相关主体公告。',
      aiInsight: '该舆情与客户当前出险预警、评级承压及持仓敞口变化存在一定关联，建议纳入重点跟踪。',
    },
    {
      id: 'sentiment-high-002',
      title: '万科部分项目交付压力增加，引发市场关注',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-15',
      updateDate: '2025-06-15',
      level: 'high',
      riskLevel: 'high',
      source: '公开舆情 / 新闻监测',
      tags: ['项目交付', '经营压力', '地产舆情'],
      summary: '部分区域项目交付节奏受到关注，可能影响客户经营稳定性和市场信心。',
      body: '近期部分区域项目交付压力增加，市场对相关项目后续进度存在关注。该事件可能对企业现金流、销售节奏和外部评级产生一定影响，建议跟踪重点项目交付进展。',
      content: '近期部分区域项目交付压力增加，市场对相关项目后续进度存在关注。该事件可能对企业现金流、销售节奏和外部评级产生一定影响，建议跟踪重点项目交付进展。',
      aiInsight: '项目交付压力可能向销售回款和品牌信用传导，建议结合区域项目清单持续跟踪。',
    },
    {
      id: 'sentiment-high-003',
      title: '万科融资环境持续承压，再融资成本上升',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-10',
      updateDate: '2025-06-10',
      level: 'high',
      riskLevel: 'high',
      source: '市场资讯 / 债券跟踪',
      tags: ['融资压力', '再融资', '评级承压'],
      summary: '外部融资环境偏紧，企业再融资成本存在上行压力。',
      body: '受行业环境和市场风险偏好影响，万科融资环境持续承压。若再融资能力继续弱化，可能影响存量债务滚续和后续兑付安排。',
      content: '受行业环境和市场风险偏好影响，万科融资环境持续承压。若再融资能力继续弱化，可能影响存量债务滚续和后续兑付安排。',
      aiInsight: '建议结合债券到期分布、融资成本变化和内部授信占用情况综合判断风险。',
    },
    {
      id: 'sentiment-high-004',
      title: '万科公开市场债务价格波动扩大',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-08',
      updateDate: '2025-06-08',
      level: 'high',
      riskLevel: 'high',
      source: '债券市场 / 舆情监测',
      tags: ['债券波动', '市场信心', '公开债务'],
      summary: '相关公开市场债务价格波动扩大，市场对后续偿债安排关注度提升。',
      body: '近期万科相关公开市场债务出现价格波动，投资者对偿债安排和展期进展保持关注。该类市场信号可能影响企业融资渠道和后续再融资成本。',
      content: '近期万科相关公开市场债务出现价格波动，投资者对偿债安排和展期进展保持关注。该类市场信号可能影响企业融资渠道和后续再融资成本。',
      aiInsight: '建议将该事件与持仓资产类型、债券敞口和评级变化联动观察。',
    },
    {
      id: 'sentiment-high-005',
      title: '万科重点城市销售回款不及预期',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-05',
      updateDate: '2025-06-05',
      level: 'high',
      riskLevel: 'high',
      source: '行业监测 / 销售数据跟踪',
      tags: ['销售回款', '现金流', '重点城市'],
      summary: '部分重点城市项目销售回款弱于预期，短期现金流修复仍存在压力。',
      body: '根据市场监测，万科部分重点城市销售回款节奏不及预期。若销售回款恢复较慢，可能影响企业经营性现金流和短债偿付安全边际。',
      content: '根据市场监测，万科部分重点城市销售回款节奏不及预期。若销售回款恢复较慢，可能影响企业经营性现金流和短债偿付安全边际。',
      aiInsight: '该舆情对现金流判断较敏感，建议与月度销售、回款和到期债务数据联合跟踪。',
    },
    {
      id: 'sentiment-high-006',
      title: '外部机构关注万科信用资质变化',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-02',
      updateDate: '2025-06-02',
      level: 'high',
      riskLevel: 'high',
      source: '评级观察 / 市场资讯',
      tags: ['评级承压', '信用资质', '外部评级'],
      summary: '外部机构持续关注万科信用资质变化，评级展望和偿债能力成为市场焦点。',
      body: '市场对万科信用资质变化保持关注，部分机构提示其融资能力、销售恢复和资产处置进展仍是关键变量。',
      content: '市场对万科信用资质变化保持关注，部分机构提示其融资能力、销售恢复和资产处置进展仍是关键变量。',
      aiInsight: '建议与评级查询模块联动，观察内部信评和外部评级之间是否存在背离。',
    },
    {
      id: 'sentiment-high-007',
      title: '万科资产处置进度低于市场预期',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-05-29',
      updateDate: '2025-05-29',
      level: 'high',
      riskLevel: 'high',
      source: '公开信息 / 资产处置跟踪',
      tags: ['资产处置', '流动性', '经营承压'],
      summary: '市场关注万科资产处置进度，若处置节奏低于预期，可能影响流动性改善。',
      body: '万科部分资产处置事项仍在推进中，市场对处置规模、回款节奏和后续流动性改善效果存在关注。',
      content: '万科部分资产处置事项仍在推进中，市场对处置规模、回款节奏和后续流动性改善效果存在关注。',
      aiInsight: '资产处置是缓解短期流动性压力的重要变量，建议纳入重点风险观察清单。',
    },
    {
      id: 'sentiment-high-008',
      title: '万科部分重点区域项目经营风险升温',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-05-24',
      updateDate: '2025-05-24',
      level: 'high',
      riskLevel: 'high',
      source: '区域舆情 / 项目监测',
      tags: ['区域风险', '项目经营', '地产压力'],
      summary: '部分重点区域项目经营表现承压，区域风险可能进一步影响整体销售和回款。',
      body: '近期部分重点区域项目经营压力上升，市场对其去化、交付和回款节奏持续关注。',
      content: '近期部分重点区域项目经营压力上升，市场对其去化、交付和回款节奏持续关注。',
      aiInsight: '建议按区域维度跟踪项目风险，重点关注与内部持仓敞口重合度较高的项目。',
    },
  ],
  medium: [
    {
      id: 'sentiment-medium-001',
      title: '万科部分区域销售回款放缓，项目去化压力增加',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-12',
      updateDate: '2025-06-12',
      level: 'medium',
      riskLevel: 'medium',
      source: '行业监测 / 销售跟踪',
      tags: ['销售回款', '项目去化', '经营压力'],
      summary: '部分区域项目销售回款节奏放缓，对短期现金流形成一定压力。',
      body: '近期部分区域项目销售回款节奏放缓，项目去化压力有所增加。该类舆情暂未形成重大风险事件，但可能影响现金流稳定性，需要持续观察。',
      content: '近期部分区域项目销售回款节奏放缓，项目去化压力有所增加。该类舆情暂未形成重大风险事件，但可能影响现金流稳定性，需要持续观察。',
      aiInsight: '该事件属于经营压力类中风险舆情，建议持续跟踪销售和回款修复情况。',
    },
    {
      id: 'sentiment-medium-002',
      title: '房地产行业政策边际调整，万科相关项目受市场关注',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-06',
      updateDate: '2025-06-06',
      level: 'medium',
      riskLevel: 'medium',
      source: '政策监测 / 行业资讯',
      tags: ['行业政策', '市场波动', '地产舆情'],
      summary: '地产行业政策变化带来市场预期波动，部分项目经营表现仍需观察。',
      body: '房地产行业政策持续调整，市场预期仍在修复过程中。万科作为重点房企，其项目销售、融资和交付情况受到市场关注。',
      content: '房地产行业政策持续调整，市场预期仍在修复过程中。万科作为重点房企，其项目销售、融资和交付情况受到市场关注。',
      aiInsight: '政策变化可能改善外部环境，但短期效果仍需结合销售数据验证。',
    },
    {
      id: 'sentiment-medium-003',
      title: '万科部分城市项目销售折扣力度加大',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-05-28',
      updateDate: '2025-05-28',
      level: 'medium',
      riskLevel: 'medium',
      source: '市场销售 / 项目监测',
      tags: ['销售折扣', '毛利承压', '经营舆情'],
      summary: '部分城市项目加大促销力度，可能对利润率形成一定压力。',
      body: '近期部分城市项目销售折扣力度加大，可能对项目毛利率和后续现金回款形成一定影响。建议结合区域销售数据持续观察。',
      content: '近期部分城市项目销售折扣力度加大，可能对项目毛利率和后续现金回款形成一定影响。建议结合区域销售数据持续观察。',
      aiInsight: '该舆情反映经营层面压力，但尚未直接构成重大信用事件。',
    },
    {
      id: 'sentiment-medium-004',
      title: '万科新增融资成本较前期小幅上行',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-17',
      updateDate: '2025-06-17',
      level: 'medium',
      riskLevel: 'medium',
      source: '融资监测 / 市场资讯',
      tags: ['融资成本', '资金价格', '中风险'],
      summary: '近期新增融资成本较前期小幅上行，资金获取难度仍需关注。',
      body: '万科新增融资成本较前期有所上行，反映外部融资环境仍存在不确定性。该变化可能对后续滚续融资形成一定影响。',
      content: '万科新增融资成本较前期有所上行，反映外部融资环境仍存在不确定性。该变化可能对后续滚续融资形成一定影响。',
      aiInsight: '建议与债务到期节奏和公开市场价格变化一起观察。',
    },
    {
      id: 'sentiment-medium-005',
      title: '万科部分项目施工进度受到市场询问',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-14',
      updateDate: '2025-06-14',
      level: 'medium',
      riskLevel: 'medium',
      source: '项目监测 / 舆情跟踪',
      tags: ['施工进度', '项目交付', '市场关注'],
      summary: '部分项目施工进度受到购房者和市场关注，但尚未形成集中负面事件。',
      body: '近期市场对万科部分项目施工进度提出关注。当前舆情仍处于观察阶段，需要结合实际交付计划判断影响。',
      content: '近期市场对万科部分项目施工进度提出关注。当前舆情仍处于观察阶段，需要结合实际交付计划判断影响。',
      aiInsight: '建议跟踪项目实际节点，避免由单点舆情扩散为区域性风险。',
    },
    {
      id: 'sentiment-medium-006',
      title: '万科存量商业资产运营表现分化',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-11',
      updateDate: '2025-06-11',
      level: 'medium',
      riskLevel: 'medium',
      source: '资产运营 / 行业观察',
      tags: ['存量资产', '运营表现', '现金流'],
      summary: '存量商业资产运营表现分化，部分资产出租和回款表现仍需观察。',
      body: '万科存量资产运营表现存在分化，优质区域资产仍具备支撑，但部分区域资产现金流贡献有限。',
      content: '万科存量资产运营表现存在分化，优质区域资产仍具备支撑，但部分区域资产现金流贡献有限。',
      aiInsight: '存量资产表现会影响经营性现金流和资产处置能力，建议持续观察。',
    },
    {
      id: 'sentiment-medium-007',
      title: '万科合作方付款节奏放缓引发关注',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-09',
      updateDate: '2025-06-09',
      level: 'medium',
      riskLevel: 'medium',
      source: '供应链舆情 / 项目监测',
      tags: ['合作方', '付款节奏', '供应链'],
      summary: '部分合作方付款节奏受到市场关注，暂未形成重大违约事件。',
      body: '近期有关万科部分合作方付款节奏放缓的舆情出现，可能与行业整体资金链压力有关。',
      content: '近期有关万科部分合作方付款节奏放缓的舆情出现，可能与行业整体资金链压力有关。',
      aiInsight: '建议关注是否向供应链稳定性和项目交付节奏传导。',
    },
    {
      id: 'sentiment-medium-008',
      title: '万科债券成交活跃度上升',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-04',
      updateDate: '2025-06-04',
      level: 'medium',
      riskLevel: 'medium',
      source: '债券市场 / 交易监测',
      tags: ['债券成交', '市场关注', '价格波动'],
      summary: '相关债券成交活跃度上升，市场关注度提高。',
      body: '万科相关债券近期成交活跃度上升，反映市场对其信用风险和偿债安排持续关注。',
      content: '万科相关债券近期成交活跃度上升，反映市场对其信用风险和偿债安排持续关注。',
      aiInsight: '该舆情属于市场关注升温信号，建议结合价格和收益率变化判断风险程度。',
    },
    {
      id: 'sentiment-medium-009',
      title: '万科管理层回应经营压力问题',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-06-01',
      updateDate: '2025-06-01',
      level: 'medium',
      riskLevel: 'medium',
      source: '公开报道 / 管理层表态',
      tags: ['管理层表态', '经营压力', '公开回应'],
      summary: '管理层就经营压力和后续安排进行回应，市场仍关注落实进度。',
      body: '万科管理层近期就经营压力、销售恢复和资产处置等问题作出回应。市场关注后续措施执行效果。',
      content: '万科管理层近期就经营压力、销售恢复和资产处置等问题作出回应。市场关注后续措施执行效果。',
      aiInsight: '该事件有助于稳定预期，但仍需跟踪实际落地情况。',
    },
    {
      id: 'sentiment-medium-010',
      title: '万科区域项目库存去化周期拉长',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-05-30',
      updateDate: '2025-05-30',
      level: 'medium',
      riskLevel: 'medium',
      source: '区域市场 / 项目监测',
      tags: ['库存去化', '销售压力', '区域市场'],
      summary: '部分区域项目库存去化周期拉长，销售修复仍需时间。',
      body: '市场数据显示，部分区域项目去化周期有所拉长。若销售恢复慢于预期，可能对现金回款产生持续影响。',
      content: '市场数据显示，部分区域项目去化周期有所拉长。若销售恢复慢于预期，可能对现金回款产生持续影响。',
      aiInsight: '建议结合重点区域项目清单和销售回款数据持续观察。',
    },
    {
      id: 'sentiment-medium-011',
      title: '万科短期债务滚续安排受到关注',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-05-26',
      updateDate: '2025-05-26',
      level: 'medium',
      riskLevel: 'medium',
      source: '债务监测 / 市场资讯',
      tags: ['短期债务', '滚续安排', '流动性'],
      summary: '短期债务滚续安排受到市场关注，相关风险仍处于观察阶段。',
      body: '万科短期债务滚续安排被市场持续关注。当前尚未形成明确负面事件，但需要跟踪再融资窗口变化。',
      content: '万科短期债务滚续安排被市场持续关注。当前尚未形成明确负面事件，但需要跟踪再融资窗口变化。',
      aiInsight: '该舆情与融资压力相关，建议作为中风险事项持续跟踪。',
    },
    {
      id: 'sentiment-medium-012',
      title: '万科部分业务板块经营数据阶段性承压',
      customer: '万科企业集团',
      customerName: '万科企业集团',
      date: '2025-05-22',
      updateDate: '2025-05-22',
      level: 'medium',
      riskLevel: 'medium',
      source: '经营数据 / 行业观察',
      tags: ['经营数据', '业务板块', '阶段性承压'],
      summary: '部分业务板块经营数据阶段性承压，需观察后续改善趋势。',
      body: '万科部分业务板块经营数据表现承压，短期内可能影响市场对企业经营恢复的判断。',
      content: '万科部分业务板块经营数据表现承压，短期内可能影响市场对企业经营恢复的判断。',
      aiInsight: '建议结合后续月度经营数据判断压力是否持续。',
    },
  ],
};
